language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: docker test
      services: docker
      script: docker run -tv ${PWD}:/project purplebabar/tarchon --info-only
    - stage: npm release
      node_js: "7"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "lalung.alexandre@gmail.com"
        api_key: $NPM_TOKEN
        on: master
